import {strict as assert} from 'node:assert';
import {globSync,mkdirSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {createTestDb,testRuntimePlugin} from './helpers/pg.mjs';
const esbuildPath=globSync('node_modules/.pnpm/esbuild@*/node_modules/esbuild/lib/main.js')[0]||'node_modules/esbuild/lib/main.js';
const esbuild=await import(pathToFileURL(esbuildPath));
mkdirSync('.sites-runtime',{recursive:true});
await esbuild.build({entryPoints:['app/api/records/route.ts'],outfile:'.sites-runtime/route-test.mjs',bundle:true,platform:'node',format:'esm',plugins:[testRuntimePlugin({auth:false})]});
const {db,pg}=await createTestDb();globalThis.testDb=db;
globalThis.testEnv={OWNER_EMAIL:'test@example.com'};
globalThis.testUser={userId:'owner-a',fullName:'Test Owner',displayName:'Test Owner',email:'test@example.com'};
const {GET,POST}=await import(pathToFileURL(process.cwd()+'/.sites-runtime/route-test.mjs'));
let assertions=0;
async function post(body,status=200,origin='https://tracker.test',workspaceId){const r=await POST(new Request('https://tracker.test/api/records',{method:'POST',headers:{'Content-Type':'application/json',origin,...(workspaceId?{'X-Workspace-Id':workspaceId}:{})},body:JSON.stringify(body)}));const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));assertions++;return d;}
async function seedMember(userId,role,workspaceId='ws:owner-a'){await pg.query('INSERT INTO workspace_members (workspace_id,user_id,role,created_at) VALUES ($1,$2,$3,$4)',[workspaceId,userId,role,new Date().toISOString()]);}
async function getWorkspace(workspaceId,status=200){const response=await GET(new Request('https://tracker.test/api/records',{headers:{'X-Workspace-Id':workspaceId}}));assert.equal(response.status,status);assertions++;return response.json();}
const c=await post({action:'create',kind:'client',data:{name:'Client A'}});
const c2=await post({action:'create',kind:'client',data:{name:'Client B'}});
const p=await post({action:'create',kind:'project',data:{name:'Campaign',clientId:c.id}});
const base={name:'Artwork',clientId:c.id,projectId:p.id,status:'En cours',due:'2026-09-10',source:'Interne'};
await post({action:'create',kind:'task',data:{...base,clientId:c2.id}},400);
await post({action:'create',kind:'task',data:{...base,due:'2026-02-30'}},400);
await post({action:'create',kind:'task',data:{...base,status:'À valider'}},400);
await post({action:'create',kind:'task',data:{...base,deliverable:'javascript:alert(1)'}},400);
await post({action:'create',kind:'task',data:{...base,assignee:'Unknown teammate'}},400);
const t=await post({action:'create',kind:'task',data:{...base,assignee:''}});
const review=await post({action:'update',kind:'task',id:t.id,revision:1,data:{...base,assignee:'',status:'À valider',deliverable:'https://example.com/art.pdf'}});
assert.equal(review.records.find(r=>r.id===t.id).status,'À valider');
await post({action:'update',kind:'task',id:t.id,revision:1,data:{...base,name:'Stale overwrite'}},409);
await post({action:'comment',taskId:t.id,text:'Please adjust the spacing.'});
const approved=await post({action:'update',kind:'task',id:t.id,revision:2,data:{...base,status:'Validé',deliverable:'https://example.com/art.pdf'}});
assert.ok(approved.records.find(r=>r.id===t.id).validatedAt);
const revised=await post({action:'update',kind:'task',id:t.id,revision:3,data:{...base,status:'Validé',deliverable:'https://example.com/revision.pdf'}});
assert.equal(revised.records.find(r=>r.id===t.id).status,'En cours');
await post({action:'update',kind:'client',id:c.id,revision:1,data:{name:'Client A',archived:true}});
await post({action:'comment',taskId:t.id,text:'Archived parent'},404);
await post({action:'update',kind:'task',id:t.id,revision:4,data:base},400);
await post({action:'update',kind:'client',id:c.id,revision:2,data:{name:'Client A',archived:false}});
await post({action:'create',kind:'client',data:{name:'Cross-origin'}},403,'https://malicious.test');
// Only an accepted invitation should create membership; role changes must not create one.
await post({action:'set-member-role',userId:'member-a',role:'creative',expectedRole:'viewer'},404);
await seedMember('member-a','viewer');
const membership=await post({action:'set-member-role',userId:'member-a',role:'creative',expectedRole:'viewer'});
assert.equal(membership.members.find(m=>m.userId==='member-a').role,'creative');
globalThis.testUser={...globalThis.testUser,userId:'member-a'};
const memberView=await (await GET(new Request('https://tracker.test/api/records'))).json();
assert.equal(memberView.workspace.role,'creative');
assert.equal(memberView.user.id,'member-a');
assert.equal(memberView.members.find(m=>m.userId==='member-a').email,'test@example.com');
assert.ok(memberView.records.some(r=>r.id===t.id));
await post({action:'create',kind:'client',data:{name:'Client created by a creative member'}},403);
await post({action:'set-member-role',userId:'owner-a',role:'viewer',expectedRole:'owner'},403);
await post({action:'remove-member',userId:'owner-a',expectedRole:'owner'},403);
await post({action:'create',kind:'project',data:{name:'Archived create',clientId:c.id,archived:true}},403);
await post({action:'update',kind:'task',id:t.id,revision:4,data:{...base,archived:true}},403);
// A member's only edit on a task is the deliverable link; every other field is read-only for them.
await post({action:'update',kind:'task',id:t.id,revision:4,data:{...base,archived:false,description:'Updated by a creative member'}},403);
const memberUpdate=await post({action:'update',kind:'task',id:t.id,revision:4,data:{...base,archived:false,deliverable:'https://example.com/member-update.pdf'}});
assert.equal(memberUpdate.records.find(r=>r.id===t.id).revision,5);
assert.equal(memberUpdate.records.find(r=>r.id===t.id).status,'À valider','saving a new deliverable link auto-sends the task for validation');
globalThis.testUser={...globalThis.testUser,userId:'owner-a'};
await post({action:'set-member-role',userId:'member-a',role:'viewer',expectedRole:'creative'});
globalThis.testUser={...globalThis.testUser,userId:'member-a'};
await post({action:'update',kind:'task',id:t.id,revision:5,data:{...base,name:'Viewer overwrite'}},403);
await post({action:'comment',taskId:t.id,text:'Viewer comment'},403);
await post({action:'set-member-role',userId:'owner-a',role:'viewer',expectedRole:'owner'},403);
await post({action:'remove-member',userId:'owner-a',expectedRole:'owner'},403);
globalThis.testUser={...globalThis.testUser,userId:'owner-a'};
const ownerView=await getWorkspace('ws:owner-a');
assert.equal(ownerView.members.find(m=>m.userId==='owner-a').name,'Test Owner');
assert.equal(ownerView.members.length,2);
for (const userId of ['owner-a',' owner-a ','\towner-a']) {
  await post({action:'set-member-role',userId,role:'viewer',expectedRole:'owner'},400);
  await post({action:'remove-member',userId,expectedRole:'owner'},400);
}
await post({action:'set-member-role',userId:'member-a',role:'owner',expectedRole:'viewer'},400);
await post({action:'set-member-role',userId:'member-a',role:'superadmin',expectedRole:'viewer'},400);
await post({action:'set-member-role',userId:'member-a',role:'admin'},400);
await post({action:'set-member-role',userId:'member-a',role:'admin',expectedRole:'creative'},409);
await post({action:'remove-member',userId:'member-a',expectedRole:'creative'},409);
await post({action:'remove-member',userId:'missing-member',expectedRole:'viewer'},404);
await post({action:'set-member-role',userId:4,role:'admin',expectedRole:'viewer'},400);
await post({action:'remove-member',userId:'x'.repeat(201),expectedRole:'viewer'},400);
await post(null,400);await post([],400);await post('invalid',400);
await post({action:'set-member-role',userId:'member-a',role:'admin',expectedRole:'viewer'});
globalThis.testUser={...globalThis.testUser,userId:'member-a'};
await post({action:'set-member-role',userId:'member-a',role:'viewer',expectedRole:'admin'},400);
await post({action:'remove-member',userId:'member-a',expectedRole:'admin'},400);
await post({action:'set-member-role',userId:'owner-a',role:'viewer',expectedRole:'owner'},400);
await post({action:'remove-member',userId:'owner-a',expectedRole:'owner'},400);
await seedMember('member-c','viewer');
await post({action:'set-member-role',userId:'member-c',role:'creative',expectedRole:'viewer'});
const removed=await post({action:'remove-member',userId:'member-c',expectedRole:'creative'});
assert.ok(!removed.members.some(m=>m.userId==='member-c'));
await post({action:'set-member-role',userId:'member-c',role:'creative',expectedRole:'viewer'},404);
globalThis.testUser={...globalThis.testUser,userId:'owner-a'};
await post({action:'remove-member',userId:'member-a',expectedRole:'admin'});
globalThis.testUser={...globalThis.testUser,userId:'member-a'};
await getWorkspace('ws:owner-a',403);
await post({action:'comment',taskId:t.id,text:'Removed member'},403,'https://tracker.test','ws:owner-a');
await post({action:'create',kind:'client',data:{name:'Stale browser'}},403,'https://tracker.test','ws:owner-a');
// A removed user can have their own workspace, but never inherit the old workspace's data.
const separateView=await (await GET(new Request('https://tracker.test/api/records'))).json();assert.notEqual(separateView.workspace.id,'ws:owner-a');assert.deepEqual(separateView.records,[]);
globalThis.testUser={...globalThis.testUser,userId:'owner-a'};
assert.equal((await getWorkspace('ws:owner-a')).records.find(r=>r.id===t.id).deliverable,'https://example.com/member-update.pdf');
// Unknown stored roles fail closed, including a corrupted owner membership.
await pg.query('UPDATE workspace_members SET role = $1 WHERE user_id = $2',['invalid','owner-a']);
assert.equal((await GET(new Request('https://tracker.test/api/records'))).status,403);
await post({action:'demo'},403);
await pg.query('UPDATE workspace_members SET role = $1 WHERE user_id = $2',['owner','owner-a']);
globalThis.testUser={...globalThis.testUser,userId:'owner-b'};
assert.deepEqual((await (await GET(new Request('https://tracker.test/api/records'))).json()).records,[]);
await getWorkspace('ws:owner-a',403);
await post({action:'remove-member',userId:'owner-a',expectedRole:'owner'},403,'https://tracker.test','ws:owner-a');
await seedMember('member-b','viewer','ws:owner-b');
await post({action:'set-member-role',userId:'member-b',role:'creative',expectedRole:'viewer'});
globalThis.testUser={...globalThis.testUser,userId:'owner-a'};
await post({action:'set-member-role',userId:'member-b',role:'admin',expectedRole:'creative'},404);
await post({action:'remove-member',userId:'member-b',expectedRole:'creative'},404);
globalThis.testUser={...globalThis.testUser,userId:'owner-b'};
await post({action:'update',kind:'task',id:t.id,revision:4,data:base},404);
await post({action:'comment',taskId:t.id,text:'Unauthorized'},404);
const demo=await post({action:'demo'});const count=demo.records.length;
assert.equal((await post({action:'demo'})).records.length,count);
const demoTask=demo.records.find(r=>r.kind==='task'&&r.status==='À valider');
const copy={...demoTask,deliverable:'',status:'Validé'};
await post({action:'update',kind:'task',id:demoTask.id,revision:1,data:copy});
globalThis.testUser=null;
assert.equal((await GET(new Request('https://tracker.test/api/records'))).status,401);
await post({action:'demo'},401);
console.log(`${assertions} API cases passed: validation, workflow, persistence, role changes, owner protection, stale changes, removal, isolation and authentication.`);
